reset-hard:
	./reset-hard.sh

reset-soft:
	./reset-soft.sh

ingress:
	./ingress.sh

help:
	@echo "Available commands:"
	@echo "  make reset-hard    - Reset the environment using reset-hard.sh"
	@echo "  make reset-soft   - Reset the environment using reset-soft.sh"
	@echo "  make ingress  - Install Ingress Controller using ingress.sh"
	@echo "  make help     - Show this help message"