apiVersion: v1
kind: Service
metadata:
  name: nodejs-api-service
spec:
  selector:
    app: nodejs-api
  ports:
    - port: 8000
      targetPort: 8000
      nodePort: 30080   # 任意で変更可（30000-32767）
  type: NodePort