apiVersion: v1
kind: Namespace
metadata:
  name: neptune
---
apiVersion: v1
kind: ServiceAccount
metadata:
  name: neptune-sa-v2
  namespace: neptune
  # 必須ではないが明示しておくと分かりやすい
secrets:
  - name: neptune-secret-1    # ↓②で作成する Secret 名を参照