apiVersion: apps/v1
kind: Deployment
metadata:
  name: api-new-c32
  namespace: neptune
spec:
  replicas: 2
  selector:
    matchLabels: { app: api-new-c32 }
  template:
    metadata:
      labels: { app: api-new-c32 }
    spec:
      containers:
        - name: backend
          image: nginx:9.99-does-not-exist   # ← タグ typo → ImagePullBackOff
          ports:
            - containerPort: 80