apiVersion: v1
kind: Pod
metadata:
  name: nginx-with-volume
spec:
  containers:
  - name: nginx
    image: nginx
    volumeMounts:
    - mountPath: /usr/share/nginx/html
      name: webcontent
  volumes:
  - name: webcontent
    persistentVolumeClaim:
      claimName: demo-pvc