apiVersion: v1
kind: Pod
metadata:
  creationTimestamp: null
  labels:
    run: pod7
  name: pod7
spec:
  containers:
  - command:
    - touch
    - /tmp/ready
    image: busybox:1.31.0
    name: pod7
    resources: {}
  dnsPolicy: ClusterFirst
  restartPolicy: Always
status: {}
