apiVersion: apps/v1
kind: Deployment
metadata:
  name: test-init
  namespace: mars          # 好きな Namespace があれば変更してください
  labels:
    app: test-init
spec:
  replicas: 1
  selector:
    matchLabels:
      app: test-init
  template:
    metadata:
      labels:
        app: test-init
    spec:
      volumes:
        - name: content-vol      # ★ nginx と InitContainer で共有するボリューム
          emptyDir: {}
      # ---- これから追加する InitContainer 用のスペース -----------------
      # initContainers:
      #   - name: init-con
      #     image: busybox:1.31.0
      #     command: ["sh", "-c", "echo 'check this out!' > /usr/share/nginx/html/index.html"]
      #     volumeMounts:
      #       - name: content-vol
      #         mountPath: /usr/share/nginx/html
      # ------------------------------------------------------------------
      containers:
        - name: nginx
          image: nginx:1.17.3-alpine
          ports:
            - containerPort: 80
          volumeMounts:
            - name: content-vol
              mountPath: /usr/share/nginx/html