apiVersion: v1
kind: Pod
metadata:
  name: curl-test
  namespace: mars
spec:
  containers:
    - name: curl
      image: nginx:alpine
      command: ["sh", "-c", "sleep infinity"]
  restartPolicy: Never