apiVersion: v1
kind: Service
metadata:
  name: manager-api-svc
  namespace: mars
spec:
  type: ClusterIP
  selector:
    app: manager-api
  ports:
    - name: http
      port: 4444          # ← クライアントがアクセスするポート
      targetPort: 8888    # ← ★ Pod 側のポートと“ズレている”ため通信できない
      protocol: TCP