apiVersion: v1
kind: Service
metadata:
  name: jupiter-crew-svc
  namespace: jupiter
spec:
  type: ClusterIP          # ← ここを NodePort に直し、nodePort: 30100 を追加する
  selector:
    app: jupiter-crew
  ports:
    - name: http
      port: 80            # サービスが公開するポート
      targetPort: 80      # Pod 側のポート
      protocol: TCP