apiVersion: v1
kind: Service
metadata:
  name: jupiter-crew-svc
  namespace: jupiter
spec:
  type: ClusterIP
  selector:
    app: jupiter-crew
  ports:
    - name: http
      port: 80
      targetPort: 80
      protocol: TCP
