apiVersion: v1
kind: Service
metadata:
  name: api
  namespace: venus
spec:
  type: ClusterIP
  selector:
    app: api
  ports:
    - name: http
      port: 2222        # Service で解決されるポート
      targetPort: 2222  # Pod 側のポート
      protocol: TCP