apiVersion: v1
kind: Pod
metadata:
  name: rbac-test
  labels:
    app: express-api
spec:
  serviceAccountName: app-sa
  containers:
    - name: nodejs-api-kubectl
      image: bitnami/kubectl
      command: ["sleep", "3600"]
  restartPolicy: Never