reset:
	./reset.sh

reset2:
	./reset2.sh

ingress:
	./ingress.sh

help:
	@echo "Available commands:"
	@echo "  make reset    - Reset the environment using reset.sh"
	@echo "  make reset2   - Reset the environment using reset2.sh"
	@echo "  make ingress  - Install Ingress Controller using ingress.sh"
	@echo "  make help     - Show this help message"