apiVersion: v1
kind: Pod
metadata:
  creationTimestamp: null
  labels:
    app: multicontainer-app
  name: multicontainer-pod
spec:
  imagePullSecrets:
  - name: ecr-registry-secret
  volumes:
  - name: shared-data
    emptyDir: {}
  containers:
  - image: 986154984217.dkr.ecr.ap-northeast-1.amazonaws.com/container-nodejs-api-8000:v1.0.5
    name: express-container
    ports:
    - containerPort: 8000
    volumeMounts:
    - name: shared-data
      mountPath: /usr/src/app/shared

  - name: busybox-sidecar
    image: busybox:latest
    command: ["/bin/sh"]
    args: ["-c", "while true; do wget -O- http://localhost:8000/posts; echo; sleep 5; done"]
    volumeMounts:
    - name: shared-data
      mountPath: /shared
  restartPolicy: Always
status: {}
