apiVersion: v1
kind: Pod
metadata:
  name: nodejs-api-pod
  labels:
    app: nodejs-api
spec:
  imagePullSecrets:
  - name: ecr-registry-secret
  containers:
    - name: nodejs-api-container
      image: 986154984217.dkr.ecr.ap-northeast-1.amazonaws.com/container-nodejs-api-8000:v1.0.5
      ports:
        - containerPort: 8000
      resources: {} # 必要に応じてリソースリクエスト/リミットを設定
  dnsPolicy: ClusterFirst
  restartPolicy: Always