---
apiVersion: v1
kind: Namespace
metadata:
  name: context
---
apiVersion: v1
kind: Pod
metadata:
  labels:
    run: secure-redis
  name: secure-redis
  namespace: context
spec:
  containers:
  - image: redis:alpine
    name: secure-redis
    securityContext:
      runAsUser: 2000
      allowPrivilegeEscalation: true
      capabilities:
        add: ["NET_ADMIN"]
