apiVersion: networking.k8s.io/v1
kind: Ingress
metadata:
  name: info-ingress
  namespace: path-ingress
spec:
  ingressClassName: nginx
  rules:
  - host: path-ingress.info
    http:
      paths:
        - backend:
            service:
              name: menu-svc
              port:
                number: 80
          path: /menu
          pathType: Prefix
        - backend:
            service:
              name: contact-svc
              port:
                number: 80
          path: /contact
          pathType: Prefix
