apiVersion: apps/v1
kind: Deployment
metadata:
  creationTimestamp: null
  labels:
    app: pod-reader
  name: pod-reader
  namespace: service
spec:
  replicas: 1
  selector:
    matchLabels:
      app: pod-reader
  template:
    metadata:
      creationTimestamp: null
      labels:
        app: pod-reader
    spec:
      serviceAccount: pod-reader-sa
      containers:
      - image: bitnami/kubectl
        name: kubectl
        command: ["sh", "-c", "while true; do kubectl get pods; sleep 5; done"]
