---
apiVersion: v1
data:
  haproxy.cfg: "frontend api_client\n  bind *:8080\n  default_backend api_backend\nbackend
    api_backend\n  server s1 api-service:9090\n  \n"
kind: ConfigMap
metadata:
  name: haproxy-cfg
  namespace: ambassador
---
apiVersion: v1
kind: Service
metadata:
  labels:
    run: api
  name: api-service
  namespace: ambassador
spec:
  ports:
  - port: 9090
    protocol: TCP
    targetPort: 80
  selector:
    run: api
  type: ClusterIP
---
apiVersion: v1
kind: Pod
metadata:
  name: frontend
  namespace: ambassador
spec:
  volumes:
  - name: config
    configMap:
      name: haproxy-cfg
  containers:
  - image: haproxy:alpine
    name: haproxy
    volumeMounts:
    - name: config
      mountPath: /usr/local/etc/haproxy
  - image: nginx:alpine
    name: frontend
    command: ["sh", "-c", "while true; do sleep 5; date && curl $SERVICE_NAME:8080 -m 2; done"]
    env:
    - name: SERVICE_NAME
      value: "localhost"
