apiVersion: v1
data:
  index.html: |
    new
kind: ConfigMap
metadata:
  name: new-index-cm
  namespace: web
---
apiVersion: apps/v1
kind: Deployment
metadata:
  labels:
    app: my-web
  name: my-web
  namespace: web
spec:
  replicas: 5
  selector:
    matchLabels:
      app: my-web
  template:
    metadata:
      labels:
        app: my-web
    spec:
      containers:
      - image: nginx
        name: nginx
        volumeMounts:
        - name: index
          mountPath: /usr/share/nginx/html
      volumes:
      - name: index
        configMap:
          name: new-index-cm
