apiVersion: batch/v1
kind: Job
metadata:
  name: hello-job
  labels:
    app: batch-job
spec:
  backoffLimit: 3
  template:
    spec:
      containers:
      - name: hello-job
        image: busybox
        command: ["echo", "Hello CKAD"]
      restartPolicy: OnFailure