apiVersion: apps/v1
kind: Deployment
metadata:
  annotations:
    deployment.kubernetes.io/revision: "1"
    kubectl.kubernetes.io/last-applied-configuration: |
      {"apiVersion":"apps/v1","kind":"Deployment","metadata":{"annotations":{},"labels":{"app":"cleaner"},"name":"cleaner","namespace":"mercury"},"spec":{"replicas":1,"selector":{"matchLabels":{"app":"cleaner"}},"template":{"metadata":{"labels":{"app":"cleaner"}},"spec":{"containers":[{"command":["sh","-c","while true; do echo \"$(date) - cleaning job ran\" \u003e\u003e /var/log/cleaner/cleaner.log; sleep 10; done"],"image":"busybox:1.31.0","name":"cleaner-con","volumeMounts":[{"mountPath":"/var/log/cleaner","name":"logs-vol"}]}],"volumes":[{"emptyDir":{},"name":"logs-vol"}]}}}}
  creationTimestamp: "2025-05-24T15:01:16Z"
  generation: 1
  labels:
    app: cleaner
  name: cleaner
  namespace: mercury
  resourceVersion: "2034"
  uid: 65e2318f-89c9-40d0-96db-8a307ddeb53d
spec:
  progressDeadlineSeconds: 600
  replicas: 1
  revisionHistoryLimit: 10
  selector:
    matchLabels:
      app: cleaner
  strategy:
    rollingUpdate:
      maxSurge: 25%
      maxUnavailable: 25%
    type: RollingUpdate
  template:
    metadata:
      creationTimestamp: null
      labels:
        app: cleaner
    spec:
      containers:
      - name: logger-con
        command: ["sh", "-c", "tail -F /var/log/cleaner/cleaner.log"]
        image: busybox:1.31.0
        volumeMounts:
        - mountPath: /var/log/cleaner
          name: logs-vol
      - command:
        - sh
        - -c
        - while true; do echo "$(date) - cleaning job ran" >> /var/log/cleaner/cleaner.log;
          sleep 10; done
        image: busybox:1.31.0
        imagePullPolicy: IfNotPresent
        name: cleaner-con
        resources: {}
        terminationMessagePath: /dev/termination-log
        terminationMessagePolicy: File
        volumeMounts:
        - mountPath: /var/log/cleaner
          name: logs-vol
      dnsPolicy: ClusterFirst
      restartPolicy: Always
      schedulerName: default-scheduler
      securityContext: {}
      terminationGracePeriodSeconds: 30
      volumes:
      - emptyDir: {}
        name: logs-vol
status:
  availableReplicas: 1
  conditions:
  - lastTransitionTime: "2025-05-24T15:01:25Z"
    lastUpdateTime: "2025-05-24T15:01:25Z"
    message: Deployment has minimum availability.
    reason: MinimumReplicasAvailable
    status: "True"
    type: Available
  - lastTransitionTime: "2025-05-24T15:01:16Z"
    lastUpdateTime: "2025-05-24T15:01:25Z"
    message: ReplicaSet "cleaner-64bbff9dd7" has successfully progressed.
    reason: NewReplicaSetAvailable
    status: "True"
    type: Progressing
  observedGeneration: 1
  readyReplicas: 1
  replicas: 1
  updatedReplicas: 1