apiVersion: v1
kind: Pod
metadata:
  name: myapp-pod
  labels:
    app: myapp-app
spec:
  containers:
  - name: myapp-container
    image: busybox:latest
    command: ["sleep", "3600"]
    envFrom:
    - configMapRef:
        name: myapp-config
    - secretRef:
        name: myapp-secret